version: 0.0
os: linux
files:
  - source: /vendor/
    destination: /home/ec2-user/serverpod/upload/vendor/
  - source: /twitter_clone_server/
    destination: /home/ec2-user/serverpod/upload/twitter_clone_server/
hooks:
  BeforeInstall:
    - location: twitter_clone_server/deploy/aws/scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: twitter_clone_server/deploy/aws/scripts/start_server
      timeout: 300
      runas: root
